version: '3.7'

services:
  grafana:
    image: grafana/grafana-enterprise:8.5.4
    container_name: yesoreyeram-infinity-datasource
    ports:
      - '3000:3000'
    volumes:
      - ./try/dashboards/:/dashboards/
      - ./try/provisioning:/etc/grafana/provisioning
      - ./dist/:/var/lib/grafana/plugins/yesoreyeram-infinity-datasource
      - ./.data:/var/lib/grafana
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
