apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    url: ''
    basicAuth: false
    jsonData:
      datasource_mode: 'basic'
